FROM node:23-alpine

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http-server ./apps/http-server

RUN pnpm run db:generate
RUN pnpm install


EXPOSE 8080 

CMD [ "pnpm", "run", "start:backend" ]

