name: Deploy web
on:
  push:
    branches: 
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: ./docker/Dockerfile.frontend
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
          push: true
          tags: thecurryguy/user-app-web:${{github.sha}}
      - name: Deploy to VM
        env: 
          DATABASE_URL: ${{secrets.DATABASE_URL}}
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@3.110.151.212 "docker pull thecurryguy/user-app-web:${{ github.sha }} && docker run --rm -e DATABASE_URL='${DATABASE_URL}' thecurryguy/user-app-web:${{ github.sha }} pnpm run db:deploy && docker stop user_web || true && docker rm user_web || true && docker run --name user_web -d -p 3000:3000 -e DATABASE_URL='${DATABASE_URL}' thecurryguy/user-app-web:${{ github.sha }}"